apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpa-deployment
  namespace: rodrigomocca
spec:
  selector:
    matchLabels:
      app: bpa
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: bpa
    spec:
      containers:
      - name: bpa
        image: registry.cloud.okteto.net/rodrigomocca/bpa_admin
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: LoadBalancer
metadata:
  namespace: rodrigomocca
  name: bpa
spec:
  selector:
    app: bpa
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
